name: Deploy site 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a file to upload
        run: |
          mkdir dist
          echo "Hello world" > dist/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployed-files
          path: dist/
