name: Deploy site 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret in masked form
        run: echo "My secret is ${{ secrets.MY_SECRET }}"
