name: Deploy site 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./deploy.sh

      - name: Run Deploy Script
        run: ./deploy.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployed-site
          path: dist/
