name: Deploy site 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./connect.sh

      - name: Run script with secret
        run: ./connect.sh "${{ secrets.MY_SECRET }}"