name: Deploy to staging

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://your-staging-url.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./stay.sh

      - name: Run Deploy Script
        run: ./stay.sh
